transport: ws

'/RiveProjectSelected':
  retain: true
  payload:
    projectId:
      type: string
    projectLabel:
      type: string
    renderer:
      type: string
      optional: true

'/RiveControlChanged':
  retain: true
  payload:
    projectId:
      type: string
    projectLabel:
      type: string
    controlName:
      type: string
    controlType:
      type: string
    source:
      type: string
    viewModel:
      type: string
      optional: true
    artboard:
      type: string
      optional: true
    stateMachine:
      type: string
      optional: true
    valueString:
      type: string
      optional: true
    valueNumber:
      type: number
      optional: true
    valueBoolean:
      type: boolean
      optional: true

'/RiveRenderQualityChanged':
  retain: true
  payload:
    scalePercent:
      type: number
    renderer:
      type: string
      optional: true

'/RiveRendererChanged':
  retain: true
  payload:
    renderer:
      type: string

'/RiveRenderStats':
  retain: true
  payload:
    renderer:
      type: string
    renderWidth:
      type: number
    renderHeight:
      type: number
    viewportWidth:
      type: number
    viewportHeight:
      type: number
    devicePixelRatio:
      type: number
    scalePercent:
      type: number
    fps:
      type: number
      optional: true
